### ISSUE TITLE
Locally stored images

### ISSUE THREAD

**Issue by aubreywullschleger** [ImperialZenta/prj-rev-bwfs-dasmoto#2]
Simplify! I would use locally stored images in your project. This is best practice for production code and makes your page load faster. To do this, you'll want to create an `images` folder inside your `resources` folder like this:
![screen shot 2017-08-24 at 7 14 12 pm](https://user-images.githubusercontent.com/11949479/29697055-b083c772-8901-11e7-88b6-2f472103bc01.png)

Then use your `<img>` tags like this:
`<img src="./resources/images/hacksaw.jpeg" alt="image of hacksaw paint brushes" >`

Also, make sure to use the `alt` attribute on your `<img>` elements (see above for example).

**Comment by ImperialZenta** [comment]
Thanks Aubrey. I incorporated this feedback for future projects.
