### ISSUE TITLE
Class attributes

### ISSUE THREAD

**Issue by aubreywullschleger** [ImperialZenta/prj-rev-bwfs-dasmoto#3]
Great! I love that you used `class` attributes on multiple elements.  This practice will help with your CSS as you are able to style multiple elements with a single selector.

Example: https://github.com/ImperialZenta/prj-rev-bwfs-dasmoto/blob/master/dasmotos/index.html#L15
https://github.com/ImperialZenta/prj-rev-bwfs-dasmoto/blob/master/dasmotos/resources/css/index.css#L17

**Comment by ImperialZenta** [comment]
Thank you for the feedback, Aubrey.
